### ISSUE TITLE
Add trash can button next to discard button on new suggestion page

### ISSUE THREAD

**Issue by fkoulen** [ASVGay/the-rhapsodies#200]
This button should empty the state so that the filled in data disappears and the whole flow is 'reset'.

**Comment by KevinBreurken** [comment]
@fkoulen Maybe this type of icon is better than a trash can one? As the option to delete a suggestion by a user might be a later requested feature for the edit-suggestion page.
![Image](https://github.com/ASVGay/the-rhapsodies/assets/4838158/356923c1-d157-4a9e-917e-566991ef23f7)

**Comment by fkoulen** [comment]
Sure. The trash can (or reset) button should only appear on the new suggestion page tho. If they want to change the whole song, they should create a new suggestion.

**Comment by KevinBreurken** [comment]
Oki, but the edit-suggestion also has the same redux logic to refil the page when returning to the same edit-suggestion. Do we want to keep that as it is / remove it /  allow to be cleared as well to the state it is in the DB?
