### ISSUE TITLE
Set up CI/CD

### ISSUE THREAD

**Issue by fkoulen** [ASVGay/the-rhapsodies#23]
# Conditional
- [ ] Project should compile
- [ ] Tests should pass
- [ ] Project is pushed to Vercel

# Optional
- [ ] Check for Sonarcloud integration
- [ ] Check for dependency scanner (snyk, dependabot)

**Comment by KevinBreurken** [comment]
Vercel requires a Pro Plan for Teams.
https://vercel.com/pricing

sent a request to create an organization for Sonarcloud, it's possible that Sonarcloud also requires a subscription. The site say's it's allowed for pubic repo's; but don't see anything about team projects.
https://docs.sonarcloud.io/managing-your-subscription/pricing/
